# Cloud Build Variables

# $PROJECT_ID

# $_LOCATION
# $_REPOSITORY
# $_IMAGE

# $_HOME
# $_SSH_STRING

steps:
  # 1. Build Docker Images
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
        "./db/",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
      ]

    # args:
    #   - -c
    #   - |
    #     docker build -t $_ZONE-docker.pkg.dev/$_REPO_NAME/$PROJECT_ID/$_IMAGE_NAME \
    #      ./db/ && docker push gcr.io/$PROJECT_ID/$_IMAGE_NAME

  # 3. Deploy via SSH to VM

options:
  logging: CLOUD_LOGGING_ONLY
