# Cloud Build Variables

# $PROJECT_ID

# $IMAGE_NAME
# $SSH_STRING
# $ZONE
# $HOME

steps:
  # 1. Build Docker Images
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME \
        -e POSTGRES_USER=$POSTGRES_USER \
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
        -e POSTGRES_DB=$POSTGRES_DB \
        -e POSTGRES_DB_TEST=$POSTGRES_DB_TEST \
         ./db/ && docker push gcr.io/$PROJECT_ID/$IMAGE_NAME

  # 3. Deploy via SSH to VM
